// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: rongstore/v1/services/rongstore_service.proto

package rongstorev1

import (
	v1 "api/common/v1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RongStoreService_StoreOwnerMutate_FullMethodName = "/rongstore.v1.RongStoreService/StoreOwnerMutate"
)

// RongStoreServiceClient is the client API for RongStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RongStoreServiceClient interface {
	StoreOwnerMutate(ctx context.Context, in *StoreOwnerMutateRequest, opts ...grpc.CallOption) (*v1.BaseResponse, error)
}

type rongStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRongStoreServiceClient(cc grpc.ClientConnInterface) RongStoreServiceClient {
	return &rongStoreServiceClient{cc}
}

func (c *rongStoreServiceClient) StoreOwnerMutate(ctx context.Context, in *StoreOwnerMutateRequest, opts ...grpc.CallOption) (*v1.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.BaseResponse)
	err := c.cc.Invoke(ctx, RongStoreService_StoreOwnerMutate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RongStoreServiceServer is the server API for RongStoreService service.
// All implementations must embed UnimplementedRongStoreServiceServer
// for forward compatibility.
type RongStoreServiceServer interface {
	StoreOwnerMutate(context.Context, *StoreOwnerMutateRequest) (*v1.BaseResponse, error)
	mustEmbedUnimplementedRongStoreServiceServer()
}

// UnimplementedRongStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRongStoreServiceServer struct{}

func (UnimplementedRongStoreServiceServer) StoreOwnerMutate(context.Context, *StoreOwnerMutateRequest) (*v1.BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreOwnerMutate not implemented")
}
func (UnimplementedRongStoreServiceServer) mustEmbedUnimplementedRongStoreServiceServer() {}
func (UnimplementedRongStoreServiceServer) testEmbeddedByValue()                          {}

// UnsafeRongStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RongStoreServiceServer will
// result in compilation errors.
type UnsafeRongStoreServiceServer interface {
	mustEmbedUnimplementedRongStoreServiceServer()
}

func RegisterRongStoreServiceServer(s grpc.ServiceRegistrar, srv RongStoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedRongStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RongStoreService_ServiceDesc, srv)
}

func _RongStoreService_StoreOwnerMutate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreOwnerMutateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RongStoreServiceServer).StoreOwnerMutate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RongStoreService_StoreOwnerMutate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RongStoreServiceServer).StoreOwnerMutate(ctx, req.(*StoreOwnerMutateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RongStoreService_ServiceDesc is the grpc.ServiceDesc for RongStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RongStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rongstore.v1.RongStoreService",
	HandlerType: (*RongStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreOwnerMutate",
			Handler:    _RongStoreService_StoreOwnerMutate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rongstore/v1/services/rongstore_service.proto",
}
