// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: rongstore/v1/services/rongstore_service.proto

package rongstorev1

import (
	v1 "api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rongstore_v1_services_rongstore_service_proto protoreflect.FileDescriptor

const file_rongstore_v1_services_rongstore_service_proto_rawDesc = "" +
	"\n" +
	"-rongstore/v1/services/rongstore_service.proto\x12\frongstore.v1\x1a\x1dcommon/v1/base_response.proto\x1a(rongstore/v1/resources/store_owner.proto2f\n" +
	"\x10RongStoreService\x12R\n" +
	"\x10StoreOwnerMutate\x12%.rongstore.v1.StoreOwnerMutateRequest\x1a\x17.common.v1.BaseResponseB\x1eZ\x1capi/rongstore/v1;rongstorev1b\x06proto3"

var file_rongstore_v1_services_rongstore_service_proto_goTypes = []any{
	(*StoreOwnerMutateRequest)(nil), // 0: rongstore.v1.StoreOwnerMutateRequest
	(*v1.BaseResponse)(nil),         // 1: common.v1.BaseResponse
}
var file_rongstore_v1_services_rongstore_service_proto_depIdxs = []int32{
	0, // 0: rongstore.v1.RongStoreService.StoreOwnerMutate:input_type -> rongstore.v1.StoreOwnerMutateRequest
	1, // 1: rongstore.v1.RongStoreService.StoreOwnerMutate:output_type -> common.v1.BaseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rongstore_v1_services_rongstore_service_proto_init() }
func file_rongstore_v1_services_rongstore_service_proto_init() {
	if File_rongstore_v1_services_rongstore_service_proto != nil {
		return
	}
	file_rongstore_v1_resources_store_owner_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rongstore_v1_services_rongstore_service_proto_rawDesc), len(file_rongstore_v1_services_rongstore_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rongstore_v1_services_rongstore_service_proto_goTypes,
		DependencyIndexes: file_rongstore_v1_services_rongstore_service_proto_depIdxs,
	}.Build()
	File_rongstore_v1_services_rongstore_service_proto = out.File
	file_rongstore_v1_services_rongstore_service_proto_goTypes = nil
	file_rongstore_v1_services_rongstore_service_proto_depIdxs = nil
}
