// Code generated by generate_errors.sh. DO NOT EDIT.
package domain
import "server/pkg/errors"

var (
	HANDSHAKE_INVALID_CLIENT_KEY = errors.BusinessError{
		Code: "AUTH-HAND-001",
		Status: 400,
		Message: "Invalid client public key",
		Severity: "S3",
		Retryable: false,
	}

	HANDSHAKE_KEY_AGREEMENT_FAIL = errors.BusinessError{
		Code: "AUTH-HAND-002",
		Status: 422,
		Message: "Key agreement failed",
		Severity: "S3",
		Retryable: false,
	}

	HANDSHAKE_RNG_FAIL = errors.BusinessError{
		Code: "AUTH-HAND-003",
		Status: 500,
		Message: "Random generation failed",
		Severity: "S1",
		Retryable: true,
	}

	HANDSHAKE_KEY_DERIVE_FAIL = errors.BusinessError{
		Code: "AUTH-HAND-004",
		Status: 500,
		Message: "Key derivation failed",
		Severity: "S1",
		Retryable: true,
	}

	HANDSHAKE_STORAGE_FAIL = errors.BusinessError{
		Code: "AUTH-HAND-005",
		Status: 500,
		Message: "Failed to store session",
		Severity: "S1",
		Retryable: true,
	}

	INVALID_CREDENTIALS = errors.BusinessError{
		Code: "AUTH-LOGIN-001",
		Status: 401,
		Message: "Invalid email or password",
		Severity: "S3",
		Retryable: false,
	}

	TOKEN_EXPIRED = errors.BusinessError{
		Code: "AUTH-TOKEN-001",
		Status: 401,
		Message: "Token expired",
		Severity: "S3",
		Retryable: false,
	}

	DB_TIMEOUT = errors.BusinessError{
		Code: "AUTH-INFRA-001",
		Status: 503,
		Message: "Service temporarily unavailable",
		Severity: "S1",
		Retryable: true,
	}

)
