// Code generated by generate_errors.sh. DO NOT EDIT.
package domain

import "server/pkg/errors"

var (
	LOGIN_EMAIL_EMPTY = errors.AppError{
		Key: "LOGIN_EMAIL_EMPTY",
		Code: "AUTH-VAL-001",
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Email is required",
		Severity: "S3",
		Retryable: false,
		Cause: "Missing email in login request",
		ClientAction: "Ask user to enter email",
		ServerAction: "Log debug; no alert",
	}

	LOGIN_EMAIL_INVALID = errors.AppError{
		Key: "LOGIN_EMAIL_INVALID",
		Code: "AUTH-VAL-002",
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid email format",
		Severity: "S3",
		Retryable: false,
		Cause: "Email does not match RFC regex",
		ClientAction: "Validate email before submitting",
		ServerAction: "Log debug for malformed input",
	}

	LOGIN_PASSWORD_EMPTY = errors.AppError{
		Key: "LOGIN_PASSWORD_EMPTY",
		Code: "AUTH-VAL-003",
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Password is required",
		Severity: "S3",
		Retryable: false,
		Cause: "Missing password in login request",
		ClientAction: "Ask user to re-enter password",
		ServerAction: "Log debug",
	}

	LOGIN_PAYLOAD_INVALID = errors.AppError{
		Key: "LOGIN_PAYLOAD_INVALID",
		Code: "AUTH-VAL-004",
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid request payload",
		Severity: "S3",
		Retryable: false,
		Cause: "Malformed JSON or missing fields",
		ClientAction: "Fix request body",
		ServerAction: "Log warn for debug purposes",
	}

	HANDSHAKE_INVALID_CLIENT_KEY = errors.AppError{
		Key: "HANDSHAKE_INVALID_CLIENT_KEY",
		Code: "AUTH-HAND-001",
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid client public key",
		Severity: "S3",
		Retryable: false,
		Cause: "Client sent malformed/unsupported public key",
		ClientAction: "Validate/generate correct key and retry",
		ServerAction: "Log warn with trace_id; no alert",
	}

	HANDSHAKE_KEY_AGREEMENT_FAIL = errors.AppError{
		Key: "HANDSHAKE_KEY_AGREEMENT_FAIL",
		Code: "AUTH-HAND-002",
		Status: 422,
		GRPCCode: "FailedPrecondition",
		Message: "Key agreement failed",
		Severity: "S3",
		Retryable: false,
		Cause: "ECDH derive failed due to incompatible/invalid key",
		ClientAction: "Regenerate keypair on supported curve",
		ServerAction: "Log warn; verify accepted curves list",
	}

	HANDSHAKE_RNG_FAIL = errors.AppError{
		Key: "HANDSHAKE_RNG_FAIL",
		Code: "AUTH-HAND-003",
		Status: 500,
		GRPCCode: "Internal",
		Message: "Random generation failed",
		Severity: "S1",
		Retryable: true,
		Cause: "System RNG failure",
		ClientAction: "Retry handshake",
		ServerAction: "Alert; investigate RNG availability",
	}

	HANDSHAKE_KEY_DERIVE_FAIL = errors.AppError{
		Key: "HANDSHAKE_KEY_DERIVE_FAIL",
		Code: "AUTH-HAND-004",
		Status: 500,
		GRPCCode: "Internal",
		Message: "Key derivation failed",
		Severity: "S1",
		Retryable: true,
		Cause: "HKDF derivation failed",
		ClientAction: "Retry handshake",
		ServerAction: "Alert; investigate HKDF process",
	}

	HANDSHAKE_STORAGE_FAIL = errors.AppError{
		Key: "HANDSHAKE_STORAGE_FAIL",
		Code: "AUTH-HAND-005",
		Status: 500,
		GRPCCode: "Internal",
		Message: "Failed to store session",
		Severity: "S1",
		Retryable: true,
		Cause: "Redis/DB failure during session storage",
		ClientAction: "Retry handshake",
		ServerAction: "Alert; check session store health",
	}

	INVALID_CREDENTIALS = errors.AppError{
		Key: "INVALID_CREDENTIALS",
		Code: "AUTH-LOGIN-001",
		Status: 401,
		GRPCCode: "Unauthenticated",
		Message: "Invalid email or password",
		Severity: "S3",
		Retryable: false,
		Cause: "Wrong credentials",
		ClientAction: "Prompt user to re-enter credentials",
		ServerAction: "Log info; consider login attempt metrics",
	}

	TOKEN_EXPIRED = errors.AppError{
		Key: "TOKEN_EXPIRED",
		Code: "AUTH-TOKEN-001",
		Status: 401,
		GRPCCode: "Unauthenticated",
		Message: "Token expired",
		Severity: "S3",
		Retryable: false,
		Cause: "Access token beyond exp",
		ClientAction: "Use refresh token or re-login",
		ServerAction: "Log info; track token expiry patterns",
	}

	DB_TIMEOUT = errors.AppError{
		Key: "DB_TIMEOUT",
		Code: "AUTH-INFRA-001",
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Database service temporarily unavailable",
		Severity: "S1",
		Retryable: true,
		Cause: "Database timeout or overload",
		ClientAction: "Retry with exponential backoff",
		ServerAction: "Alert; check DB health/capacity",
	}

	REDIS_UNAVAILABLE = errors.AppError{
		Key: "REDIS_UNAVAILABLE",
		Code: "AUTH-INFRA-002",
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Redis cache temporarily unavailable",
		Severity: "S1",
		Retryable: true,
		Cause: "Redis connection failed or timeout",
		ClientAction: "Retry operation after delay",
		ServerAction: "Alert; check Redis cluster health",
	}

	KEYCLOAK_UNAVAILABLE = errors.AppError{
		Key: "KEYCLOAK_UNAVAILABLE",
		Code: "AUTH-INFRA-003",
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Keycloak service temporarily unavailable",
		Severity: "S1",
		Retryable: true,
		Cause: "Keycloak server unreachable or timeout",
		ClientAction: "Retry authentication/authorization",
		ServerAction: "Alert; verify Keycloak server status",
	}

	POSTGRES_UNAVAILABLE = errors.AppError{
		Key: "POSTGRES_UNAVAILABLE",
		Code: "AUTH-INFRA-004",
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Postgres database service temporarily unavailable",
		Severity: "S1",
		Retryable: true,
		Cause: "Cannot connect to Postgres after multiple retries",
		ClientAction: "Retry operation after delay",
		ServerAction: "Alert; verify Postgres server health",
	}

	KEYCLOAK_CONFIG_INVALID = errors.AppError{
		Key: "KEYCLOAK_CONFIG_INVALID",
		Code: "AUTH-INFRA-005",
		Status: 500,
		GRPCCode: "Internal",
		Message: "Invalid Keycloak configuration",
		Severity: "S1",
		Retryable: false,
		Cause: "Keycloak URL/credentials/realm invalid",
		ClientAction: "Contact support",
		ServerAction: "Alert; verify Keycloak configuration",
	}

	KEYCLOAK_HEALTH_ENDPOINT_INVALID = errors.AppError{
		Key: "KEYCLOAK_HEALTH_ENDPOINT_INVALID",
		Code: "AUTH-INFRA-006",
		Status: 502,
		GRPCCode: "Unavailable",
		Message: "Invalid Keycloak health endpoint",
		Severity: "S1",
		Retryable: true,
		Cause: "Health check path incorrect or disabled",
		ClientAction: "Retry later",
		ServerAction: "Fix health endpoint configuration",
	}

	KEYCLOAK_INTERNAL = errors.AppError{
		Key: "KEYCLOAK_INTERNAL",
		Code: "AUTH-INFRA-007",
		Status: 500,
		GRPCCode: "Internal",
		Message: "Keycloak internal error",
		Severity: "S1",
		Retryable: true,
		Cause: "Keycloak returned 500 during health check or API call",
		ClientAction: "Retry operation",
		ServerAction: "Investigate Keycloak logs for root cause",
	}

	KEYCLOAK_TOKEN_REQUEST_FAIL = errors.AppError{
		Key: "KEYCLOAK_TOKEN_REQUEST_FAIL",
		Code: "AUTH-INFRA-008",
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Failed to request access token",
		Severity: "S1",
		Retryable: true,
		Cause: "Timeout or connection error when requesting token",
		ClientAction: "Retry with backoff",
		ServerAction: "Check Keycloak token endpoint",
	}

	KEYCLOAK_TOKEN_INVALID = errors.AppError{
		Key: "KEYCLOAK_TOKEN_INVALID",
		Code: "AUTH-INFRA-009",
		Status: 401,
		GRPCCode: "Unauthenticated",
		Message: "Invalid or expired Keycloak token",
		Severity: "S2",
		Retryable: false,
		Cause: "Token expired or invalid signature",
		ClientAction: "Refresh token or re-login",
		ServerAction: "Log info; track invalid token usage",
	}

	KEYCLOAK_REFRESH_TOKEN_FAIL = errors.AppError{
		Key: "KEYCLOAK_REFRESH_TOKEN_FAIL",
		Code: "AUTH-INFRA-010",
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Failed to refresh token",
		Severity: "S1",
		Retryable: true,
		Cause: "Timeout, 5xx error from Keycloak",
		ClientAction: "Retry",
		ServerAction: "Alert if occurs frequently",
	}

	KEYCLOAK_USER_NOT_FOUND = errors.AppError{
		Key: "KEYCLOAK_USER_NOT_FOUND",
		Code: "AUTH-INFRA-011",
		Status: 404,
		GRPCCode: "NotFound",
		Message: "Keycloak user not found",
		Severity: "S2",
		Retryable: false,
		Cause: "Requested user does not exist in Keycloak",
		ClientAction: "Check user ID",
		ServerAction: "Log info",
	}

	KEYCLOAK_USER_CREATE_FAIL = errors.AppError{
		Key: "KEYCLOAK_USER_CREATE_FAIL",
		Code: "AUTH-INFRA-012",
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Failed to create Keycloak user",
		Severity: "S1",
		Retryable: true,
		Cause: "Keycloak returned 5xx during user creation",
		ClientAction: "Retry",
		ServerAction: "Alert; check Keycloak user endpoints",
	}

	KEYCLOAK_USER_UPDATE_FAIL = errors.AppError{
		Key: "KEYCLOAK_USER_UPDATE_FAIL",
		Code: "AUTH-INFRA-013",
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Failed to update Keycloak user",
		Severity: "S1",
		Retryable: true,
		Cause: "5xx or timeout during update",
		ClientAction: "Retry",
		ServerAction: "Investigate Keycloak uptime",
	}

	KEYCLOAK_USER_DELETE_FAIL = errors.AppError{
		Key: "KEYCLOAK_USER_DELETE_FAIL",
		Code: "AUTH-INFRA-014",
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Failed to delete Keycloak user",
		Severity: "S1",
		Retryable: true,
		Cause: "5xx error during delete",
		ClientAction: "Retry",
		ServerAction: "Check Keycloak admin API availability",
	}

	KEYCLOAK_CLIENT_INVALID = errors.AppError{
		Key: "KEYCLOAK_CLIENT_INVALID",
		Code: "AUTH-INFRA-015",
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid Keycloak client configuration",
		Severity: "S2",
		Retryable: false,
		Cause: "Client ID/secret mismatched or missing",
		ClientAction: "Contact support",
		ServerAction: "Fix client config in Keycloak",
	}

	KEYCLOAK_REALM_NOT_FOUND = errors.AppError{
		Key: "KEYCLOAK_REALM_NOT_FOUND",
		Code: "AUTH-INFRA-016",
		Status: 404,
		GRPCCode: "NotFound",
		Message: "Keycloak realm not found",
		Severity: "S2",
		Retryable: false,
		Cause: "Realm name incorrect",
		ClientAction: "Verify realm configuration",
		ServerAction: "Log warn; validate realm list",
	}

	KEYCLOAK_ROLE_ASSIGN_FAIL = errors.AppError{
		Key: "KEYCLOAK_ROLE_ASSIGN_FAIL",
		Code: "AUTH-INFRA-017",
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Failed to assign Keycloak role",
		Severity: "S1",
		Retryable: true,
		Cause: "Keycloak role mapping API returned 5xx",
		ClientAction: "Retry",
		ServerAction: "Investigate Keycloak admin role API",
	}

	KEYCLOAK_TIMEOUT = errors.AppError{
		Key: "KEYCLOAK_TIMEOUT",
		Code: "AUTH-INFRA-018",
		Status: 504,
		GRPCCode: "DeadlineExceeded",
		Message: "Keycloak request timeout",
		Severity: "S1",
		Retryable: true,
		Cause: "Network congestion or slow Keycloak response",
		ClientAction: "Retry with backoff",
		ServerAction: "Monitor latency; check Keycloak CPU/memory",
	}

	KEYCLOAK_BAD_GATEWAY = errors.AppError{
		Key: "KEYCLOAK_BAD_GATEWAY",
		Code: "AUTH-INFRA-019",
		Status: 502,
		GRPCCode: "Unavailable",
		Message: "Bad gateway from Keycloak",
		Severity: "S1",
		Retryable: true,
		Cause: "Reverse proxy or Keycloak pod down",
		ClientAction: "Retry",
		ServerAction: "Investigate load balancer / ingress",
	}

	KEYCLOAK_GATEWAY_TIMEOUT = errors.AppError{
		Key: "KEYCLOAK_GATEWAY_TIMEOUT",
		Code: "AUTH-INFRA-020",
		Status: 504,
		GRPCCode: "DeadlineExceeded",
		Message: "Gateway timeout communicating with Keycloak",
		Severity: "S1",
		Retryable: true,
		Cause: "Request exceeded ingress/NGINX timeout",
		ClientAction: "Retry",
		ServerAction: "Increase gateway timeout or optimize endpoint",
	}

)

// ErrorByCode maps error codes to their AppError definitions
var ErrorByCode = map[string]errors.AppError{
	"AUTH-VAL-001": LOGIN_EMAIL_EMPTY,
	"AUTH-VAL-002": LOGIN_EMAIL_INVALID,
	"AUTH-VAL-003": LOGIN_PASSWORD_EMPTY,
	"AUTH-VAL-004": LOGIN_PAYLOAD_INVALID,
	"AUTH-HAND-001": HANDSHAKE_INVALID_CLIENT_KEY,
	"AUTH-HAND-002": HANDSHAKE_KEY_AGREEMENT_FAIL,
	"AUTH-HAND-003": HANDSHAKE_RNG_FAIL,
	"AUTH-HAND-004": HANDSHAKE_KEY_DERIVE_FAIL,
	"AUTH-HAND-005": HANDSHAKE_STORAGE_FAIL,
	"AUTH-LOGIN-001": INVALID_CREDENTIALS,
	"AUTH-TOKEN-001": TOKEN_EXPIRED,
	"AUTH-INFRA-001": DB_TIMEOUT,
	"AUTH-INFRA-002": REDIS_UNAVAILABLE,
	"AUTH-INFRA-003": KEYCLOAK_UNAVAILABLE,
	"AUTH-INFRA-004": POSTGRES_UNAVAILABLE,
	"AUTH-INFRA-005": KEYCLOAK_CONFIG_INVALID,
	"AUTH-INFRA-006": KEYCLOAK_HEALTH_ENDPOINT_INVALID,
	"AUTH-INFRA-007": KEYCLOAK_INTERNAL,
	"AUTH-INFRA-008": KEYCLOAK_TOKEN_REQUEST_FAIL,
	"AUTH-INFRA-009": KEYCLOAK_TOKEN_INVALID,
	"AUTH-INFRA-010": KEYCLOAK_REFRESH_TOKEN_FAIL,
	"AUTH-INFRA-011": KEYCLOAK_USER_NOT_FOUND,
	"AUTH-INFRA-012": KEYCLOAK_USER_CREATE_FAIL,
	"AUTH-INFRA-013": KEYCLOAK_USER_UPDATE_FAIL,
	"AUTH-INFRA-014": KEYCLOAK_USER_DELETE_FAIL,
	"AUTH-INFRA-015": KEYCLOAK_CLIENT_INVALID,
	"AUTH-INFRA-016": KEYCLOAK_REALM_NOT_FOUND,
	"AUTH-INFRA-017": KEYCLOAK_ROLE_ASSIGN_FAIL,
	"AUTH-INFRA-018": KEYCLOAK_TIMEOUT,
	"AUTH-INFRA-019": KEYCLOAK_BAD_GATEWAY,
	"AUTH-INFRA-020": KEYCLOAK_GATEWAY_TIMEOUT,
}
