// Code generated by generate_errors.sh. DO NOT EDIT.
package domain
import "server/pkg/errors"

var (
	EMPLOYEE_NOT_FOUND = errors.BusinessError{
		Code: "HR-EMP-001",
		Status: 404,
		Message: "Employee not found",
		Severity: "S2",
		Retryable: false,
	}

	PAYROLL_PROCESS_FAIL = errors.BusinessError{
		Code: "HR-PAY-001",
		Status: 500,
		Message: "Payroll processing failed",
		Severity: "S1",
		Retryable: true,
	}

	LEAVE_REQUEST_INVALID = errors.BusinessError{
		Code: "HR-LEAVE-001",
		Status: 400,
		Message: "Invalid leave request",
		Severity: "S3",
		Retryable: false,
	}

)
