// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common/v1/base_request.proto

package commonv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestDateTime string                 `protobuf:"bytes,1,opt,name=request_date_time,json=requestDateTime,proto3" json:"request_date_time,omitempty"`
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Language        string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	UserAgent       string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_common_v1_base_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_base_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_common_v1_base_request_proto_rawDescGZIP(), []int{0}
}

func (x *BaseRequest) GetRequestDateTime() string {
	if x != nil {
		return x.RequestDateTime
	}
	return ""
}

func (x *BaseRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BaseRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *BaseRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

var File_common_v1_base_request_proto protoreflect.FileDescriptor

const file_common_v1_base_request_proto_rawDesc = "" +
	"\n" +
	"\x1ccommon/v1/base_request.proto\x12\tcommon.v1\x1a\x1avalidate/v1/validate.proto\"\xe9\x01\n" +
	"\vBaseRequest\x12d\n" +
	"\x11request_date_time\x18\x01 \x01(\tB8\xfaB5r3\x10\x012/^(\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{2}Z)$R\x0frequestDateTime\x12'\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\trequestId\x12#\n" +
	"\blanguage\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\blanguage\x12&\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tuserAgentB\x18Z\x16api/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_base_request_proto_rawDescOnce sync.Once
	file_common_v1_base_request_proto_rawDescData []byte
)

func file_common_v1_base_request_proto_rawDescGZIP() []byte {
	file_common_v1_base_request_proto_rawDescOnce.Do(func() {
		file_common_v1_base_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_base_request_proto_rawDesc), len(file_common_v1_base_request_proto_rawDesc)))
	})
	return file_common_v1_base_request_proto_rawDescData
}

var file_common_v1_base_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_base_request_proto_goTypes = []any{
	(*BaseRequest)(nil), // 0: common.v1.BaseRequest
}
var file_common_v1_base_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_base_request_proto_init() }
func file_common_v1_base_request_proto_init() {
	if File_common_v1_base_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_base_request_proto_rawDesc), len(file_common_v1_base_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_base_request_proto_goTypes,
		DependencyIndexes: file_common_v1_base_request_proto_depIdxs,
		MessageInfos:      file_common_v1_base_request_proto_msgTypes,
	}.Build()
	File_common_v1_base_request_proto = out.File
	file_common_v1_base_request_proto_goTypes = nil
	file_common_v1_base_request_proto_depIdxs = nil
}
