// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common/v1/error.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_common_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_common_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                // AUTH-HAND-001
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                  // HANDSHAKE_INVALID_CLIENT_KEY
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                          // "Invalid client public key"
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`                        // S1/S2/S3
	Retryable     bool                   `protobuf:"varint,5,opt,name=retryable,proto3" json:"retryable,omitempty"`                     // true/false
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`                            // iam-service, gateway,...
	GrpcCode      string                 `protobuf:"bytes,7,opt,name=grpc_code,json=grpcCode,proto3" json:"grpc_code,omitempty"`        // InvalidArgument
	HttpStatus    int32                  `protobuf:"varint,8,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"` // 400, 401, 500...
	Details       []*ErrorDetail         `protobuf:"bytes,9,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_common_v1_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_common_v1_error_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Error) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Error) GetGrpcCode() string {
	if x != nil {
		return x.GrpcCode
	}
	return ""
}

func (x *Error) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *Error) GetDetails() []*ErrorDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_common_v1_error_proto protoreflect.FileDescriptor

const file_common_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x15common/v1/error.proto\x12\tcommon.v1\"Q\n" +
	"\vErrorDetail\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\x89\x02\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x1c\n" +
	"\tretryable\x18\x05 \x01(\bR\tretryable\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1b\n" +
	"\tgrpc_code\x18\a \x01(\tR\bgrpcCode\x12\x1f\n" +
	"\vhttp_status\x18\b \x01(\x05R\n" +
	"httpStatus\x120\n" +
	"\adetails\x18\t \x03(\v2\x16.common.v1.ErrorDetailR\adetailsB\x18Z\x16api/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_error_proto_rawDescOnce sync.Once
	file_common_v1_error_proto_rawDescData []byte
)

func file_common_v1_error_proto_rawDescGZIP() []byte {
	file_common_v1_error_proto_rawDescOnce.Do(func() {
		file_common_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_error_proto_rawDesc), len(file_common_v1_error_proto_rawDesc)))
	})
	return file_common_v1_error_proto_rawDescData
}

var file_common_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_v1_error_proto_goTypes = []any{
	(*ErrorDetail)(nil), // 0: common.v1.ErrorDetail
	(*Error)(nil),       // 1: common.v1.Error
}
var file_common_v1_error_proto_depIdxs = []int32{
	0, // 0: common.v1.Error.details:type_name -> common.v1.ErrorDetail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_v1_error_proto_init() }
func file_common_v1_error_proto_init() {
	if File_common_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_error_proto_rawDesc), len(file_common_v1_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_error_proto_goTypes,
		DependencyIndexes: file_common_v1_error_proto_depIdxs,
		MessageInfos:      file_common_v1_error_proto_msgTypes,
	}.Build()
	File_common_v1_error_proto = out.File
	file_common_v1_error_proto_goTypes = nil
	file_common_v1_error_proto_depIdxs = nil
}
