// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common/v1/locale.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Locale_LocaleEnum int32

const (
	Locale_UNSPECIFIED Locale_LocaleEnum = 0
	Locale_VI          Locale_LocaleEnum = 1
	Locale_EN          Locale_LocaleEnum = 2
)

// Enum value maps for Locale_LocaleEnum.
var (
	Locale_LocaleEnum_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "VI",
		2: "EN",
	}
	Locale_LocaleEnum_value = map[string]int32{
		"UNSPECIFIED": 0,
		"VI":          1,
		"EN":          2,
	}
)

func (x Locale_LocaleEnum) Enum() *Locale_LocaleEnum {
	p := new(Locale_LocaleEnum)
	*p = x
	return p
}

func (x Locale_LocaleEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Locale_LocaleEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_locale_proto_enumTypes[0].Descriptor()
}

func (Locale_LocaleEnum) Type() protoreflect.EnumType {
	return &file_common_v1_locale_proto_enumTypes[0]
}

func (x Locale_LocaleEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Locale_LocaleEnum.Descriptor instead.
func (Locale_LocaleEnum) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_locale_proto_rawDescGZIP(), []int{0, 0}
}

type Locale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locale) Reset() {
	*x = Locale{}
	mi := &file_common_v1_locale_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locale) ProtoMessage() {}

func (x *Locale) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_locale_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locale.ProtoReflect.Descriptor instead.
func (*Locale) Descriptor() ([]byte, []int) {
	return file_common_v1_locale_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_locale_proto protoreflect.FileDescriptor

const file_common_v1_locale_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/locale.proto\x12\tcommon.v1\"7\n" +
	"\x06Locale\"-\n" +
	"\n" +
	"LocaleEnum\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02VI\x10\x01\x12\x06\n" +
	"\x02EN\x10\x02B\x18Z\x16api/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_locale_proto_rawDescOnce sync.Once
	file_common_v1_locale_proto_rawDescData []byte
)

func file_common_v1_locale_proto_rawDescGZIP() []byte {
	file_common_v1_locale_proto_rawDescOnce.Do(func() {
		file_common_v1_locale_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_locale_proto_rawDesc), len(file_common_v1_locale_proto_rawDesc)))
	})
	return file_common_v1_locale_proto_rawDescData
}

var file_common_v1_locale_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_locale_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_locale_proto_goTypes = []any{
	(Locale_LocaleEnum)(0), // 0: common.v1.Locale.LocaleEnum
	(*Locale)(nil),         // 1: common.v1.Locale
}
var file_common_v1_locale_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_locale_proto_init() }
func file_common_v1_locale_proto_init() {
	if File_common_v1_locale_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_locale_proto_rawDesc), len(file_common_v1_locale_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_locale_proto_goTypes,
		DependencyIndexes: file_common_v1_locale_proto_depIdxs,
		EnumInfos:         file_common_v1_locale_proto_enumTypes,
		MessageInfos:      file_common_v1_locale_proto_msgTypes,
	}.Build()
	File_common_v1_locale_proto = out.File
	file_common_v1_locale_proto_goTypes = nil
	file_common_v1_locale_proto_depIdxs = nil
}
