// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common/v1/mutate_operation.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MutateOperation_MutateOperationEnum int32

const (
	MutateOperation_UNSPECIFIED MutateOperation_MutateOperationEnum = 0
	MutateOperation_CREATE      MutateOperation_MutateOperationEnum = 1
	MutateOperation_EDIT        MutateOperation_MutateOperationEnum = 2
	MutateOperation_DELETE      MutateOperation_MutateOperationEnum = 3
)

// Enum value maps for MutateOperation_MutateOperationEnum.
var (
	MutateOperation_MutateOperationEnum_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "CREATE",
		2: "EDIT",
		3: "DELETE",
	}
	MutateOperation_MutateOperationEnum_value = map[string]int32{
		"UNSPECIFIED": 0,
		"CREATE":      1,
		"EDIT":        2,
		"DELETE":      3,
	}
)

func (x MutateOperation_MutateOperationEnum) Enum() *MutateOperation_MutateOperationEnum {
	p := new(MutateOperation_MutateOperationEnum)
	*p = x
	return p
}

func (x MutateOperation_MutateOperationEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutateOperation_MutateOperationEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_mutate_operation_proto_enumTypes[0].Descriptor()
}

func (MutateOperation_MutateOperationEnum) Type() protoreflect.EnumType {
	return &file_common_v1_mutate_operation_proto_enumTypes[0]
}

func (x MutateOperation_MutateOperationEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutateOperation_MutateOperationEnum.Descriptor instead.
func (MutateOperation_MutateOperationEnum) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_mutate_operation_proto_rawDescGZIP(), []int{0, 0}
}

type MutateOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateOperation) Reset() {
	*x = MutateOperation{}
	mi := &file_common_v1_mutate_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateOperation) ProtoMessage() {}

func (x *MutateOperation) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_mutate_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateOperation.ProtoReflect.Descriptor instead.
func (*MutateOperation) Descriptor() ([]byte, []int) {
	return file_common_v1_mutate_operation_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_mutate_operation_proto protoreflect.FileDescriptor

const file_common_v1_mutate_operation_proto_rawDesc = "" +
	"\n" +
	" common/v1/mutate_operation.proto\x12\tcommon.v1\"[\n" +
	"\x0fMutateOperation\"H\n" +
	"\x13MutateOperationEnum\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\b\n" +
	"\x04EDIT\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03B\x18Z\x16api/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_mutate_operation_proto_rawDescOnce sync.Once
	file_common_v1_mutate_operation_proto_rawDescData []byte
)

func file_common_v1_mutate_operation_proto_rawDescGZIP() []byte {
	file_common_v1_mutate_operation_proto_rawDescOnce.Do(func() {
		file_common_v1_mutate_operation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_mutate_operation_proto_rawDesc), len(file_common_v1_mutate_operation_proto_rawDesc)))
	})
	return file_common_v1_mutate_operation_proto_rawDescData
}

var file_common_v1_mutate_operation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_mutate_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_mutate_operation_proto_goTypes = []any{
	(MutateOperation_MutateOperationEnum)(0), // 0: common.v1.MutateOperation.MutateOperationEnum
	(*MutateOperation)(nil),                  // 1: common.v1.MutateOperation
}
var file_common_v1_mutate_operation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_mutate_operation_proto_init() }
func file_common_v1_mutate_operation_proto_init() {
	if File_common_v1_mutate_operation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_mutate_operation_proto_rawDesc), len(file_common_v1_mutate_operation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_mutate_operation_proto_goTypes,
		DependencyIndexes: file_common_v1_mutate_operation_proto_depIdxs,
		EnumInfos:         file_common_v1_mutate_operation_proto_enumTypes,
		MessageInfos:      file_common_v1_mutate_operation_proto_msgTypes,
	}.Build()
	File_common_v1_mutate_operation_proto = out.File
	file_common_v1_mutate_operation_proto_goTypes = nil
	file_common_v1_mutate_operation_proto_depIdxs = nil
}
