// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"server/internal/iam/application/usecases"
	"server/internal/iam/infrastructure/repositories"
	"server/internal/iam/interface/grpc"
	"server/pkg/config"
)

// Injectors from wire.go:

func InitializeIamHandler() (*grpc.IamHandler, error) {
	configConfig := config.Load()
	db, err := config.NewGormDB(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewGormRepository(db)
	loginUserUsecase := usecases.NewLoginUserUsecase(userRepository)
	handshakeUsecase := usecases.NewHandshakeUsecase(userRepository)
	iamHandler := grpc.NewIamHandler(loginUserUsecase, handshakeUsecase)
	return iamHandler, nil
}
