// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"server/internal/iam/application/usecases"
	"server/internal/iam/infrastructure/cache"
	"server/internal/iam/infrastructure/client"
	"server/internal/iam/infrastructure/db"
	"server/internal/iam/infrastructure/errors"
	"server/internal/iam/infrastructure/eventbus"
	"server/internal/iam/infrastructure/repositories"
	"server/internal/iam/interface/grpc"
	"server/pkg/config"
)

// Injectors from wire.go:

func InitializeIamHandler(ctx context.Context) IamDeps {
	configConfig := config.Load()
	businessError := errors.InitBusinessError(configConfig)
	gormDB := db.InitGormPostgresDB(ctx, configConfig, businessError)
	userRepository := repositories.NewGormUserRepository(gormDB)
	keycloak := client.InitKeycloakClient(ctx, configConfig, businessError)
	loginUsecase := usecases.NewLoginUsecase(userRepository, keycloak)
	redisSessionStore := cache.InitRedisSessionStore(configConfig)
	handshakeUsecase := usecases.NewHandshakeUsecase(userRepository, redisSessionStore)
	iamHandler := grpc.NewIamHandler(loginUsecase, handshakeUsecase)
	rabbitMQEventBus := eventbus.InitRabbitMQEventBus(configConfig)
	iamDeps := IamDeps{
		Handler:           iamHandler,
		RedisSessionStore: redisSessionStore,
		Keycloak:          keycloak,
		EventBus:          rabbitMQEventBus,
		BusinessError:     businessError,
	}
	return iamDeps
}
