// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: rongstore/v1/resources/store_owner.proto

package rongstorev1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreOwner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: gorm:"column:KHOA"
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// @gotags: gorm:"column:Stt"
	LineNumber int32 `protobuf:"varint,2,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	// @gotags: gorm:"column:MaVT"
	ProductCode string `protobuf:"bytes,3,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	// @gotags: gorm:"column:TenVT"
	ProductName string `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	// @gotags: gorm:"column:Dvt"
	Unit string `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	// @gotags: gorm:"column:SoLuong"
	Quantity float32 `protobuf:"fixed32,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// @gotags: gorm:"column:DonGia"
	Price float32 `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	// @gotags: gorm:"column:ThanhTien"
	TotalAmount float32 `protobuf:"fixed32,8,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	// @gotags: gorm:"column:ThanhToanTinhThue"
	TaxIncludedAmount float32 `protobuf:"fixed32,9,opt,name=tax_included_amount,json=taxIncludedAmount,proto3" json:"tax_included_amount,omitempty"`
	// @gotags: gorm:"column:LoaiThue"
	TaxType string `protobuf:"bytes,10,opt,name=tax_type,json=taxType,proto3" json:"tax_type,omitempty"`
	// @gotags: gorm:"column:ThueSuat"
	TaxRate float32 `protobuf:"fixed32,11,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	// @gotags: gorm:"column:GhiChu"
	Description string `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	// @gotags: gorm:"column:NhanVienCKMH"
	StaffId int32 `protobuf:"varint,13,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	// @gotags: gorm:"column:CREATE_BY"
	CreateBy int32 `protobuf:"varint,14,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	// @gotags: gorm:"column:UPDATE_BY"
	UpdateBy int32 `protobuf:"varint,15,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	// @gotags: gorm:"column:CREATE_DATE"
	CreateDate string `protobuf:"bytes,16,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	// @gotags: gorm:"column:UPDATE_DATE"
	UpdateDate string `protobuf:"bytes,17,opt,name=update_date,json=updateDate,proto3" json:"update_date,omitempty"`
	// @gotags: gorm:"column:Ngay"
	Date          string `protobuf:"bytes,18,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreOwner) Reset() {
	*x = StoreOwner{}
	mi := &file_rongstore_v1_resources_store_owner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreOwner) ProtoMessage() {}

func (x *StoreOwner) ProtoReflect() protoreflect.Message {
	mi := &file_rongstore_v1_resources_store_owner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreOwner.ProtoReflect.Descriptor instead.
func (*StoreOwner) Descriptor() ([]byte, []int) {
	return file_rongstore_v1_resources_store_owner_proto_rawDescGZIP(), []int{0}
}

func (x *StoreOwner) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *StoreOwner) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *StoreOwner) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *StoreOwner) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *StoreOwner) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *StoreOwner) GetQuantity() float32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StoreOwner) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StoreOwner) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *StoreOwner) GetTaxIncludedAmount() float32 {
	if x != nil {
		return x.TaxIncludedAmount
	}
	return 0
}

func (x *StoreOwner) GetTaxType() string {
	if x != nil {
		return x.TaxType
	}
	return ""
}

func (x *StoreOwner) GetTaxRate() float32 {
	if x != nil {
		return x.TaxRate
	}
	return 0
}

func (x *StoreOwner) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StoreOwner) GetStaffId() int32 {
	if x != nil {
		return x.StaffId
	}
	return 0
}

func (x *StoreOwner) GetCreateBy() int32 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *StoreOwner) GetUpdateBy() int32 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *StoreOwner) GetCreateDate() string {
	if x != nil {
		return x.CreateDate
	}
	return ""
}

func (x *StoreOwner) GetUpdateDate() string {
	if x != nil {
		return x.UpdateDate
	}
	return ""
}

func (x *StoreOwner) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type StoreOwnerMutateRequest struct {
	state         protoimpl.MessageState                               `protogen:"open.v1"`
	Data          *StoreOwnerMutateRequest_StoreOwnerMutateRequestData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreOwnerMutateRequest) Reset() {
	*x = StoreOwnerMutateRequest{}
	mi := &file_rongstore_v1_resources_store_owner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreOwnerMutateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreOwnerMutateRequest) ProtoMessage() {}

func (x *StoreOwnerMutateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rongstore_v1_resources_store_owner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreOwnerMutateRequest.ProtoReflect.Descriptor instead.
func (*StoreOwnerMutateRequest) Descriptor() ([]byte, []int) {
	return file_rongstore_v1_resources_store_owner_proto_rawDescGZIP(), []int{1}
}

func (x *StoreOwnerMutateRequest) GetData() *StoreOwnerMutateRequest_StoreOwnerMutateRequestData {
	if x != nil {
		return x.Data
	}
	return nil
}

type StoreOwnerMutateRequest_StoreOwnerMutateOneOf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Mutation:
	//
	//	*StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Create
	//	*StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Update
	//	*StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Delete
	Mutation      isStoreOwnerMutateRequest_StoreOwnerMutateOneOf_Mutation `protobuf_oneof:"mutation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreOwnerMutateRequest_StoreOwnerMutateOneOf) Reset() {
	*x = StoreOwnerMutateRequest_StoreOwnerMutateOneOf{}
	mi := &file_rongstore_v1_resources_store_owner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreOwnerMutateRequest_StoreOwnerMutateOneOf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreOwnerMutateRequest_StoreOwnerMutateOneOf) ProtoMessage() {}

func (x *StoreOwnerMutateRequest_StoreOwnerMutateOneOf) ProtoReflect() protoreflect.Message {
	mi := &file_rongstore_v1_resources_store_owner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreOwnerMutateRequest_StoreOwnerMutateOneOf.ProtoReflect.Descriptor instead.
func (*StoreOwnerMutateRequest_StoreOwnerMutateOneOf) Descriptor() ([]byte, []int) {
	return file_rongstore_v1_resources_store_owner_proto_rawDescGZIP(), []int{1, 0}
}

func (x *StoreOwnerMutateRequest_StoreOwnerMutateOneOf) GetMutation() isStoreOwnerMutateRequest_StoreOwnerMutateOneOf_Mutation {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *StoreOwnerMutateRequest_StoreOwnerMutateOneOf) GetCreate() *StoreOwner {
	if x != nil {
		if x, ok := x.Mutation.(*StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *StoreOwnerMutateRequest_StoreOwnerMutateOneOf) GetUpdate() *StoreOwner {
	if x != nil {
		if x, ok := x.Mutation.(*StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *StoreOwnerMutateRequest_StoreOwnerMutateOneOf) GetDelete() *StoreOwner {
	if x != nil {
		if x, ok := x.Mutation.(*StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isStoreOwnerMutateRequest_StoreOwnerMutateOneOf_Mutation interface {
	isStoreOwnerMutateRequest_StoreOwnerMutateOneOf_Mutation()
}

type StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Create struct {
	Create *StoreOwner `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Update struct {
	Update *StoreOwner `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Delete struct {
	Delete *StoreOwner `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

func (*StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Create) isStoreOwnerMutateRequest_StoreOwnerMutateOneOf_Mutation() {
}

func (*StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Update) isStoreOwnerMutateRequest_StoreOwnerMutateOneOf_Mutation() {
}

func (*StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Delete) isStoreOwnerMutateRequest_StoreOwnerMutateOneOf_Mutation() {
}

type StoreOwnerMutateRequest_StoreOwnerMutateRequestData struct {
	state         protoimpl.MessageState                           `protogen:"open.v1"`
	Mutations     []*StoreOwnerMutateRequest_StoreOwnerMutateOneOf `protobuf:"bytes,1,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreOwnerMutateRequest_StoreOwnerMutateRequestData) Reset() {
	*x = StoreOwnerMutateRequest_StoreOwnerMutateRequestData{}
	mi := &file_rongstore_v1_resources_store_owner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreOwnerMutateRequest_StoreOwnerMutateRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreOwnerMutateRequest_StoreOwnerMutateRequestData) ProtoMessage() {}

func (x *StoreOwnerMutateRequest_StoreOwnerMutateRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_rongstore_v1_resources_store_owner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreOwnerMutateRequest_StoreOwnerMutateRequestData.ProtoReflect.Descriptor instead.
func (*StoreOwnerMutateRequest_StoreOwnerMutateRequestData) Descriptor() ([]byte, []int) {
	return file_rongstore_v1_resources_store_owner_proto_rawDescGZIP(), []int{1, 1}
}

func (x *StoreOwnerMutateRequest_StoreOwnerMutateRequestData) GetMutations() []*StoreOwnerMutateRequest_StoreOwnerMutateOneOf {
	if x != nil {
		return x.Mutations
	}
	return nil
}

var File_rongstore_v1_resources_store_owner_proto protoreflect.FileDescriptor

const file_rongstore_v1_resources_store_owner_proto_rawDesc = "" +
	"\n" +
	"(rongstore/v1/resources/store_owner.proto\x12\frongstore.v1\x1a\x1avalidate/v1/validate.proto\"\xaa\x04\n" +
	"\n" +
	"StoreOwner\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vline_number\x18\x02 \x01(\x05R\n" +
	"lineNumber\x12!\n" +
	"\fproduct_code\x18\x03 \x01(\tR\vproductCode\x12!\n" +
	"\fproduct_name\x18\x04 \x01(\tR\vproductName\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x02R\bquantity\x12\x14\n" +
	"\x05price\x18\a \x01(\x02R\x05price\x12!\n" +
	"\ftotal_amount\x18\b \x01(\x02R\vtotalAmount\x12.\n" +
	"\x13tax_included_amount\x18\t \x01(\x02R\x11taxIncludedAmount\x12\x19\n" +
	"\btax_type\x18\n" +
	" \x01(\tR\ataxType\x12\x19\n" +
	"\btax_rate\x18\v \x01(\x02R\ataxRate\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12\x19\n" +
	"\bstaff_id\x18\r \x01(\x05R\astaffId\x12\x1b\n" +
	"\tcreate_by\x18\x0e \x01(\x05R\bcreateBy\x12\x1b\n" +
	"\tupdate_by\x18\x0f \x01(\x05R\bupdateBy\x12\x1f\n" +
	"\vcreate_date\x18\x10 \x01(\tR\n" +
	"createDate\x12\x1f\n" +
	"\vupdate_date\x18\x11 \x01(\tR\n" +
	"updateDate\x12\x12\n" +
	"\x04date\x18\x12 \x01(\tR\x04date\"\xc6\x03\n" +
	"\x17StoreOwnerMutateRequest\x12_\n" +
	"\x04data\x18\x01 \x01(\v2A.rongstore.v1.StoreOwnerMutateRequest.StoreOwnerMutateRequestDataB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04data\x1a\xc4\x01\n" +
	"\x15StoreOwnerMutateOneOf\x122\n" +
	"\x06create\x18\x01 \x01(\v2\x18.rongstore.v1.StoreOwnerH\x00R\x06create\x122\n" +
	"\x06update\x18\x02 \x01(\v2\x18.rongstore.v1.StoreOwnerH\x00R\x06update\x122\n" +
	"\x06delete\x18\x03 \x01(\v2\x18.rongstore.v1.StoreOwnerH\x00R\x06deleteB\x0f\n" +
	"\bmutation\x12\x03\xf8B\x01\x1a\x82\x01\n" +
	"\x1bStoreOwnerMutateRequestData\x12c\n" +
	"\tmutations\x18\x01 \x03(\v2;.rongstore.v1.StoreOwnerMutateRequest.StoreOwnerMutateOneOfB\b\xfaB\x05\x92\x01\x02\b\x01R\tmutationsB\x1eZ\x1capi/rongstore/v1;rongstorev1b\x06proto3"

var (
	file_rongstore_v1_resources_store_owner_proto_rawDescOnce sync.Once
	file_rongstore_v1_resources_store_owner_proto_rawDescData []byte
)

func file_rongstore_v1_resources_store_owner_proto_rawDescGZIP() []byte {
	file_rongstore_v1_resources_store_owner_proto_rawDescOnce.Do(func() {
		file_rongstore_v1_resources_store_owner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rongstore_v1_resources_store_owner_proto_rawDesc), len(file_rongstore_v1_resources_store_owner_proto_rawDesc)))
	})
	return file_rongstore_v1_resources_store_owner_proto_rawDescData
}

var file_rongstore_v1_resources_store_owner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rongstore_v1_resources_store_owner_proto_goTypes = []any{
	(*StoreOwner)(nil),                                          // 0: rongstore.v1.StoreOwner
	(*StoreOwnerMutateRequest)(nil),                             // 1: rongstore.v1.StoreOwnerMutateRequest
	(*StoreOwnerMutateRequest_StoreOwnerMutateOneOf)(nil),       // 2: rongstore.v1.StoreOwnerMutateRequest.StoreOwnerMutateOneOf
	(*StoreOwnerMutateRequest_StoreOwnerMutateRequestData)(nil), // 3: rongstore.v1.StoreOwnerMutateRequest.StoreOwnerMutateRequestData
}
var file_rongstore_v1_resources_store_owner_proto_depIdxs = []int32{
	3, // 0: rongstore.v1.StoreOwnerMutateRequest.data:type_name -> rongstore.v1.StoreOwnerMutateRequest.StoreOwnerMutateRequestData
	0, // 1: rongstore.v1.StoreOwnerMutateRequest.StoreOwnerMutateOneOf.create:type_name -> rongstore.v1.StoreOwner
	0, // 2: rongstore.v1.StoreOwnerMutateRequest.StoreOwnerMutateOneOf.update:type_name -> rongstore.v1.StoreOwner
	0, // 3: rongstore.v1.StoreOwnerMutateRequest.StoreOwnerMutateOneOf.delete:type_name -> rongstore.v1.StoreOwner
	2, // 4: rongstore.v1.StoreOwnerMutateRequest.StoreOwnerMutateRequestData.mutations:type_name -> rongstore.v1.StoreOwnerMutateRequest.StoreOwnerMutateOneOf
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_rongstore_v1_resources_store_owner_proto_init() }
func file_rongstore_v1_resources_store_owner_proto_init() {
	if File_rongstore_v1_resources_store_owner_proto != nil {
		return
	}
	file_rongstore_v1_resources_store_owner_proto_msgTypes[2].OneofWrappers = []any{
		(*StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Create)(nil),
		(*StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Update)(nil),
		(*StoreOwnerMutateRequest_StoreOwnerMutateOneOf_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rongstore_v1_resources_store_owner_proto_rawDesc), len(file_rongstore_v1_resources_store_owner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rongstore_v1_resources_store_owner_proto_goTypes,
		DependencyIndexes: file_rongstore_v1_resources_store_owner_proto_depIdxs,
		MessageInfos:      file_rongstore_v1_resources_store_owner_proto_msgTypes,
	}.Build()
	File_rongstore_v1_resources_store_owner_proto = out.File
	file_rongstore_v1_resources_store_owner_proto_goTypes = nil
	file_rongstore_v1_resources_store_owner_proto_depIdxs = nil
}
