// Code generated by generate_errors.sh. DO NOT EDIT.
package domain

import "server/pkg/errors"

var (
	EMPLOYEE_NOT_FOUND = errors.BusinessError{
		Key: "EMPLOYEE_NOT_FOUND",
		Code: "HR-EMP-001",
		Status: 404,
		GRPCCode: "NotFound",
		Message: "Employee not found",
		Severity: "S2",
		Retryable: false,
		Cause: "Invalid employee ID",
		ClientAction: "Check employee ID",
		ServerAction: "Log info; monitor invalid access attempts",
	}

	PAYROLL_PROCESS_FAIL = errors.BusinessError{
		Key: "PAYROLL_PROCESS_FAIL",
		Code: "HR-PAY-001",
		Status: 500,
		GRPCCode: "Internal",
		Message: "Payroll processing failed",
		Severity: "S1",
		Retryable: true,
		Cause: "DB or external service failure",
		ClientAction: "Retry later",
		ServerAction: "Alert finance ops; investigate DB/services",
	}

	LEAVE_REQUEST_INVALID = errors.BusinessError{
		Key: "LEAVE_REQUEST_INVALID",
		Code: "HR-LEAVE-001",
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid leave request",
		Severity: "S3",
		Retryable: false,
		Cause: "Invalid date or quota",
		ClientAction: "Correct leave request",
		ServerAction: "Log debug; track invalid requests",
	}

)

// ErrorByCode maps error codes to their BusinessError definitions
var ErrorByCode = map[string]errors.BusinessError{
	"HR-EMP-001": EMPLOYEE_NOT_FOUND,
	"HR-PAY-001": PAYROLL_PROCESS_FAIL,
	"HR-LEAVE-001": LEAVE_REQUEST_INVALID,
}
