// Code generated by generate_errors.sh. DO NOT EDIT.
package errors

var (
	UNKNOWN_DOMAIN_KEY = AppError{
		Key: "UNKNOWN_DOMAIN_KEY",
		Code: "AUTH-VAL-999",
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Unknown domain error",
		Severity: "S1",
		Retryable: false,
	}

	INTERNAL_FALLBACK = AppError{
		Key: "INTERNAL_FALLBACK",
		Code: "CORE-INF-000",
		Status: 500,
		GRPCCode: "Internal",
		Message: "Internal server error",
		Severity: "S1",
		Retryable: false,
	}

)

// ErrorByCode maps default error codes to their AppError definitions
var ErrorByCode = map[string]AppError{
	"AUTH-VAL-999": UNKNOWN_DOMAIN_KEY,
	"CORE-INF-000": INTERNAL_FALLBACK,
}
