#!/usr/bin/env bash
set -e

YAML_FILE="../business_errors.yaml"

services=$(yq e '.services | keys | .[]' "$YAML_FILE")

for svc in $services; do
    OUTPUT_FILE="../internal/$svc/domain/default_errors_gen.go"
    mkdir -p "$(dirname "$OUTPUT_FILE")"
    [ -f "$OUTPUT_FILE" ] && rm "$OUTPUT_FILE"

    echo "// Code generated by generate_errors.sh. DO NOT EDIT." > "$OUTPUT_FILE"
    echo "package domain" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "import \"server/pkg/errors\"" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"

    echo "var (" >> "$OUTPUT_FILE"

    # Mảng chứa key + code
    error_keys=()

    # Main loop (KHÔNG dùng subshell)
    while IFS="|" read -r key code status message severity retryable; do
        error_keys+=("$key:$code")

        {
            echo -e "\t${key} = errors.BusinessError{"
            echo -e "\t\tCode: \"$code\","
            echo -e "\t\tStatus: $status,"
            echo -e "\t\tMessage: \"$message\","
            echo -e "\t\tSeverity: \"$severity\","
            echo -e "\t\tRetryable: $retryable,"
            echo -e "\t}"
            echo ""
        } >> "$OUTPUT_FILE"

    done < <(
        yq e ".services.$svc.errors | .. | select(tag==\"!!seq\") | .[]" -j "$YAML_FILE" |
        jq -r '.key + "|" + .code + "|" + (.http_status|tostring) + "|" + .message + "|" + (.severity // "") + "|" + (.retryable // false | tostring)'
    )

    # --- Thêm defaults ---
    defaults=$(yq e ".defaults" -j "$YAML_FILE" | jq -r 'to_entries[] | "\(.key)|\(.value.code)|\(.value.http_status)|\(.value.message)|S1|false"')
    while IFS="|" read -r key code status message severity retryable; do
        error_keys+=("$key:$code")
        {
            echo -e "\t${key} = errors.BusinessError{"
            echo -e "\t\tCode: \"$code\","
            echo -e "\t\tStatus: $status,"
            echo -e "\t\tMessage: \"$message\","
            echo -e "\t\tSeverity: \"$severity\","
            echo -e "\t\tRetryable: $retryable,"
            echo -e "\t}"
            echo ""
        } >> "$OUTPUT_FILE"
    done <<< "$defaults"
    # --- end defaults ---

    echo ")" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"

    echo "// ErrorByCode maps error codes to their BusinessError definitions" >> "$OUTPUT_FILE"
    echo "var ErrorByCode = map[string]errors.BusinessError{" >> "$OUTPUT_FILE"

    for pair in "${error_keys[@]}"; do
        key="${pair%%:*}"
        code="${pair##*:}"
        echo -e "\t\"$code\": $key," >> "$OUTPUT_FILE"
    done

    echo "}" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"

    # Thêm GetErrorByCode
    echo "// GetErrorByCode returns an error by code" >> "$OUTPUT_FILE"
    echo "func GetErrorByCode(code string) (errors.BusinessError, bool) {" >> "$OUTPUT_FILE"
    echo "    err, ok := ErrorByCode[code]" >> "$OUTPUT_FILE"
    echo "    return err, ok" >> "$OUTPUT_FILE"
    echo "}" >> "$OUTPUT_FILE"

    echo "" >> "$OUTPUT_FILE"

    # Thêm GetBusinessError
    echo "// GetBusinessError converts an error to BusinessError if possible" >> "$OUTPUT_FILE"
    echo "func GetBusinessError(err error) (*errors.BusinessError, bool) {" >> "$OUTPUT_FILE"
    echo "    if be, ok := err.(*errors.BusinessError); ok {" >> "$OUTPUT_FILE"
    echo "        return be, true" >> "$OUTPUT_FILE"
    echo "    }" >> "$OUTPUT_FILE"
    echo "    return &UNKNOWN_DOMAIN_KEY, false" >> "$OUTPUT_FILE"
    echo "}" >> "$OUTPUT_FILE"

    echo "" >> "$OUTPUT_FILE"

    echo "Generated $OUTPUT_FILE successfully!"
    
done
