#!/usr/bin/env bash
set -e

YAML_FILE="../business_errors.yaml"

# --- Lặp qua từng service ---

services=$(yq e '.services | keys | .[]' "$YAML_FILE")

for svc in $services; do
OUTPUT_FILE="../internal/$svc/domain/default_errors_gen.go"
mkdir -p "$(dirname "$OUTPUT_FILE")"
[ -f "$OUTPUT_FILE" ] && rm "$OUTPUT_FILE"

```
echo "// Code generated by generate_errors.sh. DO NOT EDIT." > "$OUTPUT_FILE"
echo "package domain" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "import \"server/pkg/errors\"" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "var (" >> "$OUTPUT_FILE"

# --- Array chứa key:code để tạo map ---
error_keys=()

# --- Process service errors ---
while IFS="|" read -r key code status grpc_code message severity retryable cause client_action server_action; do
    error_keys+=("$key:$code")
    {
        echo -e "\t${key} = errors.AppError{"
        echo -e "\t\tKey: \"$key\","
        echo -e "\t\tCode: \"$code\","
        echo -e "\t\tStatus: $status,"
        echo -e "\t\tGRPCCode: \"$grpc_code\","
        echo -e "\t\tMessage: \"$message\","
        echo -e "\t\tSeverity: \"$severity\","
        echo -e "\t\tRetryable: $retryable,"
        echo -e "\t\tCause: \"$cause\","
        echo -e "\t\tClientAction: \"$client_action\","
        echo -e "\t\tServerAction: \"$server_action\","
        echo -e "\t}"
        echo ""
    } >> "$OUTPUT_FILE"
done < <(
    yq e ".services.$svc.errors | .. | select(tag==\"!!seq\") | .[]" -o=json "$YAML_FILE" |
    jq -r '.key + "|" + .code + "|" + (.http_status|tostring) + "|" + .grpc_code + "|" + .message + "|" + (.severity // "") + "|" + (.retryable // false | tostring) + "|" + (.cause // "") + "|" + (.client_action // "") + "|" + (.server_action // "")'
)

echo ")" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# --- Tạo map ErrorByCode ---
echo "// ErrorByCode maps error codes to their AppError definitions" >> "$OUTPUT_FILE"
echo "var ErrorByCode = map[string]errors.AppError{" >> "$OUTPUT_FILE"
for pair in "${error_keys[@]}"; do
    key="${pair%%:*}"
    code="${pair##*:}"
    echo -e "\t\"$code\": $key," >> "$OUTPUT_FILE"
done
echo "}" >> "$OUTPUT_FILE"
echo ""
```

done

# --- Process defaults ---

OUTPUT_DEFAULT_FILE="../pkg/errors/default_errors_gen.go"
mkdir -p "$(dirname "$OUTPUT_DEFAULT_FILE")"
[ -f "$OUTPUT_DEFAULT_FILE" ] && rm "$OUTPUT_DEFAULT_FILE"

echo "// Code generated by generate_errors.sh. DO NOT EDIT." > "$OUTPUT_DEFAULT_FILE"
echo "package errors" >> "$OUTPUT_DEFAULT_FILE"
echo "" >> "$OUTPUT_DEFAULT_FILE"
echo "var (" >> "$OUTPUT_DEFAULT_FILE"

# --- Array chứa key:code cho map ---

# Lấy dữ liệu defaults vào biến tạm
defaults_data=$(yq e ".defaults" -o=json "$YAML_FILE" | jq -r '
to_entries[] | "\(.key)|\(.value.code)|\(.value.http_status)|\(.value.grpc_code)|\(.value.message)|S1|false|\(.value.cause // "")|\(.value.client_action // "")|\(.value.server_action // "")"
')

# Dùng process substitution để while không chạy trong subshell
while IFS="|" read -r key code status grpc_code message severity retryable cause client_action server_action; do
    default_keys+=("$key:$code")
    {
        echo -e "\t$key = AppError{"
        echo -e "\t\tKey: \"$key\","
        echo -e "\t\tCode: \"$code\","
        echo -e "\t\tStatus: $status,"
        echo -e "\t\tGRPCCode: \"$grpc_code\","
        echo -e "\t\tMessage: \"$message\","
        echo -e "\t\tSeverity: \"$severity\","
        echo -e "\t\tRetryable: $retryable,"
        echo -e "\t}"
        echo ""
    } >> "$OUTPUT_DEFAULT_FILE"
done < <(echo "$defaults_data")
echo ")" >> "$OUTPUT_DEFAULT_FILE"
echo "" >> "$OUTPUT_DEFAULT_FILE"

# --- Tạo map ErrorByCode ---
echo "// ErrorByCode maps default error codes to their AppError definitions" >> "$OUTPUT_DEFAULT_FILE"
echo "var ErrorByCode = map[string]AppError{" >> "$OUTPUT_DEFAULT_FILE"
for pair in "${default_keys[@]}"; do
    key="${pair%%:*}"
    code="${pair##*:}"
    echo -e "\t\"$code\": $key," >> "$OUTPUT_DEFAULT_FILE"
done

echo "}" >> "$OUTPUT_DEFAULT_FILE"
