#!/usr/bin/env bash
set -e

YAML_FILE="../business_errors.yaml"

services=$(yq e '.services | keys | .[]' "$YAML_FILE")

for svc in $services; do
    OUTPUT_FILE="../internal/$svc/domain/default_errors_gen.go"
    mkdir -p "$(dirname "$OUTPUT_FILE")"
    [ -f "$OUTPUT_FILE" ] && rm "$OUTPUT_FILE"

    echo "// Code generated by generate_errors.sh. DO NOT EDIT." > "$OUTPUT_FILE"
    echo "package domain" >> "$OUTPUT_FILE"
    echo 'import "server/pkg/errors"' >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "var (" >> "$OUTPUT_FILE"

    # Duyệt tất cả errors trong service, flatten bằng JSON
    yq e ".services.$svc.errors | .. | select(tag==\"!!seq\") | .[]" -j "$YAML_FILE" | \
    jq -r '.key + "|" + .code + "|" + (.http_status|tostring) + "|" + .message + "|" + (.severity // "") + "|" + (.retryable // false | tostring)' | \
    while IFS="|" read -r key code status message severity retryable; do
        echo -e "\t$key = errors.BusinessError{" >> "$OUTPUT_FILE"
        echo -e "\t\tCode: \"$code\"," >> "$OUTPUT_FILE"
        echo -e "\t\tStatus: $status," >> "$OUTPUT_FILE"
        echo -e "\t\tMessage: \"$message\"," >> "$OUTPUT_FILE"
        echo -e "\t\tSeverity: \"$severity\"," >> "$OUTPUT_FILE"
        echo -e "\t\tRetryable: $retryable," >> "$OUTPUT_FILE"
        echo -e "\t}" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    done

    echo ")" >> "$OUTPUT_FILE"
    echo "Generated $OUTPUT_FILE successfully!"
done
